version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  producer:
    image: fmancini/producer
    build:
      context: ./producer
    environment:
      - "TIME_RANGE=3"
      - "FLINK_URL=jobmanager:8081"
    volumes:
      - "./producer/data:/producer/data"
    depends_on:
      - kafka
      - jobmanager

  consumer:
    image: fmancini/consumer
    build:
      context: ./consumer
    volumes:
      - "./consumer/output:/output"
    depends_on:
      - kafka

  jobmanager:
    image: flink:latest
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - "../target:/target"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.latency.interval: 1
        metrics.latency.granularity: single
        metrics.reporter.grph.factory.class: org.apache.flink.metrics.graphite.GraphiteReporterFactory
        metrics.reporter.grph.host: graphite
        metrics.reporter.grph.port: 2003
        metrics.reporter.grph.protocol: TCP
        metrics.reporter.grph.interval: 60 SECONDS
    depends_on:
      - graphite

  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        metrics.latency.interval: 5000
        metrics.latency.granularity: single
        metrics.reporter.grph.factory.class: org.apache.flink.metrics.graphite.GraphiteReporterFactory
        metrics.reporter.grph.host: graphite
        metrics.reporter.grph.port: 2003
        metrics.reporter.grph.protocol: TCP
        metrics.reporter.grph.interval: 60 SECONDS

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
